#!/bin/bash
# Quick start guide for HunyuanVideo-1.5
# Usage: source quick_start.sh

echo "=========================================="
echo "HunyuanVideo-1.5 Quick Start"
echo "=========================================="
echo ""

# Load environment
echo "Loading environment..."
. setup_env.sh

echo ""
echo "=========================================="
echo "Environment Ready!"
echo "=========================================="
echo ""
echo "Common Commands:"
echo ""
echo "1. Text-to-Video (720p, 50 steps):"
echo "   python generate.py \\"
echo "     --prompt 'A beautiful landscape with mountains' \\"
echo "     --resolution 720p \\"
echo "     --model_path ./ckpts"
echo ""
echo "2. Image-to-Video (720p, 50 steps):"
echo "   python generate.py \\"
echo "     --prompt 'Camera zooms in on the image' \\"
echo "     --image_path ./input.png \\"
echo "     --resolution 720p \\"
echo "     --model_path ./ckpts"
echo ""
echo "3. Fast Generation (480p I2V, 8 steps with step-distill):"
echo "   python generate.py \\"
echo "     --image_path ./input.png \\"
echo "     --resolution 480p \\"
echo "     --enable_step_distill \\"
echo "     --num_inference_steps 8 \\"
echo "     --model_path ./ckpts"
echo ""
echo "4. With CFG Distilled (faster, ~2x speedup):"
echo "   python generate.py \\"
echo "     --prompt 'Your prompt' \\"
echo "     --resolution 720p \\"
echo "     --cfg_distilled \\"
echo "     --model_path ./ckpts"
echo ""
echo "5. Help:"
echo "   python generate.py --help"
echo ""
echo "=========================================="
echo ""
echo "For prompt enhancement, set these env variables:"
echo "  export T2V_REWRITE_BASE_URL='<your_vllm_server>'"
echo "  export T2V_REWRITE_MODEL_NAME='Qwen3-235B-A22B-Thinking-2507'"
echo ""
echo "For more info, see README.md"
